# Generated by Django 5.0.1 on 2024-08-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_vid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BallData',
        ),
    ]
