# Generated by Django 5.0.1 on 2024-08-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps', models.FloatField()),
                ('ball_count', models.IntegerField()),
                ('frame', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
